### ISSUE TITLE
Share to Diaspora* inserts "+" instead of spaces in titles

### ISSUE THREAD

**Issue by wazoox** [Mte90/Share-Backported#117]
This is a behaviour introduced with version 2.0.x. Version 1.3.0 works fine.

Example sharing this page to Diaspora*  initializes the windows with the following text:

```
### New+Issue+·+Mte90/Share-Backported

https://github.com/Mte90/Share-Backported/issues/new

```

What's expected instead (what happened with version 1.30):

```
### New Issue · Mte90/Share-Backported

https://github.com/Mte90/Share-Backported/issues/new

```
Confirmed across several users. Downgrading to 1.3.0 fixes the problem.

**Comment by Mte90** [comment]
We have a specific code for diaspora but seems that is not executed https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js#L243 I will work on that.

**Comment by wazoox** [comment]
Thanks for the quick fix friends :)

**Comment by Mte90** [comment]
:-D

**Comment by wazoox** [comment]
Today's update broke Diaspora sharing again :/

**Comment by Mte90** [comment]
It is this line that create issues, should be on top https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js#L268

**Comment by Mte90** [comment]
Fixed in the last release

**Comment by wazoox** [comment]
Sorry, the problem is still there (v.  2.0.6). Tried on two machines,
restarted Firefox, no dice.

**Comment by Ryuno-Ki** [comment]
Hm, `+` would be a space in `encodeURIComponent` …

@Mte90 Let me know, if you need a hand here :-)

**Comment by Mte90** [comment]
On my tests the url is ok: `https://share.diasporafoundation.org/?url=https%3A%2F%2Fdaniele.tech%2Fita%2F&title=Home+-+Daniele+Mte90+Scasciafratte`
The encode anyway is happening at the top before do the fixes for the various shares.

**Comment by Mte90** [comment]
I don't have an account on diaspora to see what is happening

**Comment by wazoox** [comment]
Here's a screenshot (running the current version):
http://imgur.com/Ap6JoX4l.png

**Comment by Mte90** [comment]
No I found a wrong variable used in diaspora -.-'

**Comment by wazoox** [comment]
I hereby confirm 2 .0.7 works fine :) Thanks @Mte90  :+1:

**Comment by wazoox** [comment]
Hello, version 2.1.0 upgrade today reintroduced this bug!

**Comment by Mte90** [comment]
Very strange the code is there https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js#L319

I am opening back the ticket to study the situation.

**Comment by wazoox** [comment]
You could check the latest posts from my friend Jay :
https://diasp.eu/people/a0863370a7790131339411719cc2cd82
:)

**Comment by wazoox** [comment]
Thanks, I'll check it out!

Cheers
Emmanuel

**Comment by Mte90** [comment]
There is a new release with a fix, in my tests should be fixed now.
